### ISSUE TITLE
Cannot scale up/down a service with Rancher Compose

### ISSUE THREAD

**Issue by nixelsolutions** [rancher/rancher-compose#56]
Hi,

Using rancher-compose scale option doesn't update service scale, this is the current output:

```bash
rancher-compose --debug -f /var/lib/nico/compose/12345/sv9qct-eu/docker-compose.yml -r /var/lib/nico/compose/12345/sv9qct-eu/rancher-compose.yml -p 12345 scale
DEBU[0000] Opening compose file: /var/lib/nico/compose/12345/sv9qct-eu/docker-compose.yml
DEBU[0000] Opening rancher-compose file: /var/lib/nico/compose/12345/sv9qct-eu/rancher-compose.yml
DEBU[0000] Found environment: 12345(1e19)
```

How can I change a service scale with rancher compose?

In previous rancher-compose versions I could change scale setting by just executing rancher-compose create, and I also used it to update environment variables. Is there any chance we could use a flag to recover this behavior? It was very useful to be able to update environment variables without recreating the service nor upgrading it.

Thanks!

**Comment by deniseschannon** [comment]
The syntax is 
`rancher-compose scale servicename=number`

https://docs.docker.com/v1.6/compose/cli/#scale

I'm not sure how you were previously able to update environment variables because once a service is created, we don't allow editing environment variables. Since docker containers can't be changed once they are created, we mimic the same behavior.

**Comment by nixelsolutions** [comment]
Thanks! Maybe I'm confused with the fact that I was able to update scale by executing the create or start command, I don't remember. I had also to set -p [project_name] if service is in a stack different from default.
